kind: pipeline
type: docker
name: default

steps:
  - name: build_env
    image: node:18.15.0
    commands:
      - echo "$NPMRC" > .npmrc
      - echo NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL" >> .env
      - echo NEXT_PUBLIC_API_CLIENT_ID="$NEXT_PUBLIC_API_CLIENT_ID" >> .env
      - echo NEXT_PUBLIC_API_CLIENT_SECRET="$NEXT_PUBLIC_API_CLIENT_SECRET" >> .env
      - echo NEXTAUTH_SECRET="$NEXTAUTH_SECRET" >> .env
      - echo NEXTAUTH_URL="$NEXTAUTH_URL" >> .env
      - echo API_URL="$API_URL" >> .env
    environment:
        NPMRC:
            from_secret: NPMRC
        NEXT_PUBLIC_API_URL:
            from_secret: NEXT_PUBLIC_API_URL
        NEXT_PUBLIC_API_CLIENT_ID:
            from_secret: NEXT_PUBLIC_API_CLIENT_ID
        NEXT_PUBLIC_API_CLIENT_SECRET:
            from_secret: NEXT_PUBLIC_API_CLIENT_SECRET
        NEXTAUTH_SECRET:
            from_secret: NEXTAUTH_SECRET
        NEXTAUTH_URL:
            from_secret: NEXTAUTH_URL
        API_URL:
            from_secret: API_URL

  - name: install
    image: node:18.15.0
    commands:
      - yarn install
#      - yarn build
    environment:
        NPMRC:
            from_secret: NPMRC

  - name: test
    image: node:18.15.0
    commands:
        - yarn lint
        - yarn prettier