[phases.setup]
cmds = [
  "echo '@fortawesome:registry=https://npm.fontawesome.com/' > .npmrc",
  "echo '@awesome.me:registry=https://npm.fontawesome.com/' >> .npmrc",
  "echo '//npm.fontawesome.com/:_authToken=${FONTAWESOME_PACKAGE_TOKEN}' >> .npmrc"
]

[phases.build]
cmds = ["yarn", "yarn build", "chmod +x start.sh"]

[phases.start]
cmds = ["yarn add -g pm2", "./start.sh"]