[phases.setup]
cmds = [
  "echo '@fortawesome:registry=https://npm.fontawesome.com/' > .npmrc",
  "echo '@awesome.me:registry=https://npm.fontawesome.com/' >> .npmrc",
  "echo '//npm.fontawesome.com/:_authToken=${FONTAWESOME_PACKAGE_TOKEN}' >> .npmrc"
]

[phases.start]
cmds = ["yarn global add pm2"]

[phases.build]
cmds = ["yarn build"]

[phases.start]
cmds = ["yarn start:pm2"]
